name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        cmake . -B build
        cmake --build build

