name: Build

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        cmake . -B build
        cmake --build build

