name: Build

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        cmake . -B build -DSCL_BUILD_DOCUMENTATION=OFF
        cmake --build build

    - name: Test
      shell: bash
      run: cmake --build build --target test
