name: Checks

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  headers:
    name: headers
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Copyright
        run: ./scripts/check_copyright_headers.py

      - name: Header Guards
        run: ./scripts/check_header_guards.py

  style:
    name: style
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: sudo apt-get install -y clang-format-15

      - name: Check
        shell: bash
        run: ./scripts/check_formatting.sh
