name: Checks

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: sudo apt-get install -y doxygen

      - name: Documentation
        shell: bash
        run: ./scripts/build_documentation.sh

  headers:
    name: Header files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copyright
        run: ./scripts/check_copyright_headers.py

      - name: Header Guards
        run: ./scripts/check_header_guards.py

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: sudo apt-get install -y clang-format-12

      - name: Check
        shell: bash
        run: |
          find . -type f \( -iname "*.h" -o -iname "*.cc" \) -exec clang-format -n --style=Google {} \; &> checks.txt
          cat checks.txt
          test ! -s checks.txt
