name: Documentation

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  documentation:
    name: documentation
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache doxygen
        id: cache-doxygen
        uses: actions/cache@v4
        with:
          path: ~/doxygen
          key: ${{ runner.os }}-doxygen

      - name: Install doxygen
        if: ${{ steps.cache-doxygen.outputs.cache-hit != 'true' }}
        run: |
          curl https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz -o doxygen.tar.gz
          mkdir ~/doxygen
          tar xf doxygen.tar.gz -C ~/doxygen --strip-components=1

      - name: Generate documentation
        shell: bash
        run: |
          cmake . -B build -DSCL_BUILD_TESTS=OFF -DSCL_DOXYGEN_BIN=$HOME/doxygen/bin/doxygen
          cmake --build build --target documentation
