name: Test

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Coverage and Linting
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt-get install -y lcov bear
        curl -L https://github.com/catchorg/Catch2/archive/v2.13.0.tar.gz -o c.tar.gz
        tar xvf c.tar.gz
        cd Catch2-2.13.0/
        cmake -B catch -DBUILD_TESTING=OFF
        cmake --build catch
        sudo cmake --install catch

    - name: CMake
      run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE .

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: bear make -s -j4

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Coverage
      shell: bash
      run: |
        cmake --build ${{runner.workspace}}/build --target coverage
        lcov --summary ${{runner.workspace}}/build/coverage.info >> ${{runner.workspace}}/summary.txt
        ./scripts/check_coverage.py ${{runner.workspace}}/summary.txt

    - name: Lint
      shell: bash
      run: |
        find include/ src/ test/ -type f \( -iname "*.h" -o -iname "*.cc" \) \
        -exec clang-tidy -p ${{runner.workspace}}/build/compile_commands.json --quiet {} \; 1>> lint.txt 2>/dev/null
        cat lint.txt
        test ! -s lint.txt

